# ============================================================
# DATABASE SQL Server
# ============================================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Sapo_Clone;encrypt=false
spring.datasource.username=sa
spring.datasource.password=MaiVanNam1102005

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN



# ============================================================
# JWT
# ============================================================
jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e9f8o7n6m5l4k3j2i1h0g9f8e7d6c5b4a3210zy

jwt.expiration=86400000

# ============================================================
# Cloudinary
# ============================================================
cloudinary.cloud_name=dh8xlfsvq
cloudinary.api_key=843247926469719
cloudinary.api_secret=fTxyFmzxZGmOnYTDQ1c2Q2sFcxU

# ============================================================
# Goong API
# ============================================================
goong.api.key=sA0fGkaJYhYlaHMzJPyfMu5ZrWTe5KrQpItCdskH
goong.api.base-url=https://rsapi.goong.io

# ============================================================
# REDIS
# ============================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ============================================================
# EMAIL (SMTP)
# ============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lamprrro1234@gmail.com
spring.mail.password=onaerwpsoesbiqsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# General App Settings
# ============================================================
spring.application.name=Sapo_Clone
server.port=8080
logging.level.com.example.Sapo_Clone=DEBUG
logging.level.org.springframework.security=INFO
app.security.allowed-origins=http://localhost:3000,http://localhost:5173
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
