# ============================================================
# DATABASE SQL Server
# ============================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN



# ============================================================
# JWT
# ============================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ============================================================
# Cloudinary
# ============================================================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# ============================================================
# Goong API
# ============================================================
goong.api.key=${GOONG_API_KEY}
goong.api.base-url=https://rsapi.goong.io

# ============================================================
# REDIS
# ============================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ============================================================
# EMAIL (SMTP)
# ============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# General App Settings
# ============================================================
spring.application.name=Sapo_Clone
server.port=8080
logging.level.com.example.Sapo_Clone=DEBUG
logging.level.org.springframework.security=INFO
app.security.allowed-origins=http://localhost:3000,http://localhost:5173
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
