name: Deploy Backend Sapo_Clone

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Kéo code mới nhất từ GitHub về máy chủ
        uses: actions/checkout@v4

      - name: 2. Thiết lập môi trường Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: 2.3 Tự động tạo file .env từ GitHub Secrets
        shell: powershell
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "GOONG_API_KEY=${{ secrets.GOONG_API_KEY }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> .env

      - name: 3. Dừng server cũ
        run: taskkill /F /IM java.exe /T
        continue-on-error: true

      - name: 4. Đóng gói dự án (Build file JAR)
        run: .\mvnw.cmd clean package -DskipTests

      - name: 5. Khởi động ứng dụng (Chạy ngầm với cấu hình đầy đủ)
        shell: powershell
        run: |
          $jarPath = "target\Sapo_Clone-0.0.1-SNAPSHOT.jar"
          # Mảng các tham số khởi động
          $argList = @("-jar", $jarPath)
          
          # Khởi động tiến trình và hướng log ra file để bạn debug
          Start-Process -FilePath "java" -ArgumentList $argList -WorkingDirectory (Get-Location).Path -RedirectStandardOutput "full_log.txt" -RedirectStandardError "error_log.txt"