name: Deploy Backend Sapo_Clone

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Kéo code mới nhất từ GitHub về máy chủ
        uses: actions/checkout@v4

      - name: 2. Thiết lập môi trường Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: 2.3 Tự động tạo file .env từ GitHub Secrets
        shell: powershell
        run: |
            echo "DB_URL=${{ secrets.DB_URL }}" > .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
            echo "GOONG_API_KEY=${{ secrets.GOONG_API_KEY }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

      - name: 3. Dừng server cũ (giải phóng file JAR đang bị khóa)
        run: taskkill /F /IM java.exe /T
        continue-on-error: true

      - name: 4. Đóng gói dự án (Build file JAR)
        run: .\mvnw.cmd clean package -DskipTests

      - name: 5. Tạo file .env từ GitHub Secrets
        shell: powershell
        run: |
          $envContent = @"
          DB_URL=${{ secrets.DB_URL }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          GOONG_API_KEY=${{ secrets.GOONG_API_KEY }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          "@
          $envContent | Out-File -FilePath ".env" -Encoding UTF8 -NoNewline
          Write-Host "Da tao file .env thanh cong!"

      - name: 6. Khởi động lại máy chủ Backend
        shell: powershell
        run: |
          $jarFile = Get-ChildItem -Path target\*.jar | Select-Object -First 1
          if ($jarFile) {
              $env:RUNNER_TRACKING_ID = $null
              Start-Process -FilePath "java" -ArgumentList "-jar `"$($jarFile.FullName)`"" -WindowStyle Hidden
              Write-Host "Da khoi dong lai Backend: $($jarFile.Name) thanh cong!"
          } else {
              Write-Error "Khong tim thay file jar trong thu muc target!"
              exit 1
          }